
<div class="cgu">
    <div class="cgu_content">
        <h1>Conditions de service SportLink</h1>
        <div class="cgu_title">
            <h3>1. Les services que nous fournissons</h3>
            <p>Notre mission est d’offrir la possibilité de construire une communauté et de rapprocher le monde. Pour mener à bien cette mission, nous vous fournissons les Produits décrits ci-dessous.</p>
        </div>
        <div class="cgu_description">
            <h4>Nous fournissons, personnalisons et améliorons nos Produits :</h4>
            <p>
                votre expérience sur SpotLink est unique et ne ressemble à celle de personne d’autre, qu’il s’agisse des publications, des stories, des évènements, des publicités (si nous vous affichons des publicités sur les Produits) et des autres contenus que vous voyez dans le fil d’actualité SportLink ou sur notre plateforme vidéo, ou des Pages SportLink auxquelles vous êtes abonné et des autres fonctionnalités que vous pouvez utiliser, telles que la barre de recherche. Par exemple, nous utilisons les informations à propos des connexions que vous établissez, des options et des paramètres que vous sélectionnez, et de ce que vous partagez et faites sur nos Produits et en dehors pour personnaliser votre expérience.
                Veuillez consulter notre Politique de confidentialité afin d’en savoir plus sur la manière dont nous utilisons les informations pour vous offrir une expérience personnalisée.
                Nous vous aidons à trouver et à contacter les personnes, les groupes, les entreprises, les organisations et autres qui comptent pour vous sur l’ensemble des Produits que vous utilisez. Nous utilisons les informations dont nous disposons pour vous présenter des suggestions, par exemple des groupes à rejoindre, des évènements auxquels participer, des Pages SporLink auxquelles s’abonner ou envoyer un message, des programmes à regarder et des personnes avec lesquelles vous pourriez vouloir devenir ami. Les meilleures communautés sont fondées sur des liens forts et nous pensons que nos Produits sont plus utiles lorsque les utilisateurs sont connectés aux personnes, aux groupes et aux organisations qui comptent pour eux. Nous voulons que le contenu et les suggestions que vous voyez sur SportLink soient aussi intéressants et utiles que possible. Veuillez consulter les Fiches système de nos systèmes de recommandation pour obtenir des informations sur la manière dont nos différents systèmes de recommandation hiérarchisent les signaux afin de déterminer le contenu et les suggestions à vous présenter, ainsi que sur les options permettant de personnaliser votre expérience.
                Nous vous montrons des offres et d’autres contenus commerciaux ou sponsorisés afin de vous aider à découvrir du contenu, des produits et des services qui sont proposés par les nombreuses entreprises et organisations qui utilisent SportLink et d’autres Produits afin de vous aider à découvrir des contenus, des produits et des services qui pourraient vous intéresser.
                La section 2 ci-dessous offre des explications plus détaillées.
                Nos Produits fournissent de nombreuses manières de vous exprimer ou de communiquer avec vos amis, votre famille et d’autres personnes à propos de ce qui compte pour vous, par exemple le partage de statuts, de photos, de vidéos et de stories à travers les Produits (conformément à vos paramètres), l’envoi de messages, les appels vocaux ou vidéo avec un ami ou plusieurs personnes, la création d’évènements ou de groupes, l’ajout de contenu à votre profil, ainsi que l’affichage de la manière dont les autres réagissent à votre contenu. Nous avons également développé de nouvelles manières d’utiliser la technologie, telles que la réalité augmentée et la vidéo 360 pour créer et partager des contenus plus expressifs et attrayants sur les Produits, et nous continuons d’explorer cette voie.
                Nous nous impliquons dans la recherche pour développer, tester et améliorer nos Produits. Cela inclut d’analyser les informations que nous avons concernant nos utilisateurs et d’en apprendre plus sur l’utilisation de nos Produits, par exemple, en effectuant des sondages et des tests et en résolvant les problèmes qui surviennent dans de nouvelles fonctionnalités. Nous utilisons et développons des technologies avancées, telles que l’intelligence artificielle, les systèmes d’apprentissage automatique et la réalité augmentée, afin que les personnes puissent utiliser nos Produits en toute sécurité, indépendamment de toute aptitude physique ou de tout emplacement géographique. Par exemple, de telles technologies aident les personnes malvoyantes à comprendre quelles sont les personnes ou les choses présentes dans les photos ou les vidéos partagées sur SportLink. Nous créons également une technologie sophistiquée de réseau et de communication pour aider davantage d’utilisateurs à se connecter à Internet dans les régions présentant un accès limité. Et nous développons des systèmes automatisés pour renforcer notre capacité à protéger notre communauté et nos Produits.
                Veuillez consulter notre Politique de confidentialité afin d’en savoir plus sur la manière dont nous utilisons vos informations pour offrir, développer et améliorer les produits.
            </p>

            <h4>Nous favorisons la sûreté, la sécurité et l’intégrité de nos Produits, luttons contre les comportements préjudiciables et assurons la sécurité de notre communauté d’utilisateurs :</h4>
            <p>
                Les personnes ne formeront une communauté sur les Produits que si elles s’y sentent en sécurité et protégées. Nous mettons tout en œuvre pour préserver la sécurité (y compris la disponibilité, l’authenticité, l’intégrité et la confidentialité) de nos Produits et services. Nous employons des équipes dédiées à travers le monde, collaborons avec des partenaires, des fournisseurs de services externes et d’autres entités pertinentes et développons des systèmes techniques avancés afin de détecter les éventuelles mauvaises utilisations de nos Produits, les comportements préjudiciables à autrui et les situations dans lesquelles nous pourrions être en mesure de soutenir ou de protéger notre communauté, y compris pour répondre aux signalements d’infractions potentielles que nous envoient les utilisateurs. Si un tel contenu ou un tel comportement est porté à notre connaissance, nous pourrons prendre les mesures appropriées, notamment en vous avertissant, en vous proposant notre aide, en supprimant ou restreignant le contenu, en supprimant ou en limitant l’accès à certaines fonctionnalités, en désactivant un compte ou en contactant les forces de l’ordre. Pour en savoir plus sur les restrictions que nous pouvons imposer à l’utilisation de SportLink, y compris sur la façon dont nous appliquons nos politiques de contenu, nos procédures, nos mesures et nos outils, cliquez ici. Nous partageons des informations avec d’autres entités lorsque nous identifions une utilisation abusive ou un comportement préjudiciable de la part d’un utilisateur de l’un de nos Produits, ou pour contribuer à la sécurité des Produits, des utilisateurs et de la communauté. Par exemple, nous partageons des informations avec les entités fournissant des produits et services financiers afin de les aider à promouvoir la sécurité, la protection et l’intégrité ainsi qu’à respecter la loi applicable peut consulter, conserver, utiliser et partager toute information qu’elle recueille à votre sujet si elle estime de bonne foi que la loi l’exige ou l’autorise à le faire. Pour en apprendre davantage, veuillez consulter notre Politique de confidentialité.
                Dans certains cas, le Conseil de surveillance peut examiner les décisions que nous avons prises, sous réserve de ses conditions et de ses statuts.
            </p>

            <h4>Nous fournissons des expériences homogènes et fluides sur les Produits des entités, en dehors du contrat que nous avons conclu avec vous :</h4>
            <p>
                Nous concevons nos systèmes pour que votre expérience soit homogène et fluide à travers l’ensemble des différents Produits des entités que vous utilisez, et ce, selon vos choix. Par exemple, nous utilisons des informations à propos des personnes avec lesquelles vous interagissez sur SportLink afin de faciliter vos communications avec celles-ci dans la messagerie, et nous vous permettons de communiquer au moyen de cette même messagerie avec une entreprise à laquelle vous êtes abonné sur SportLink.
            </p>

            <h4>Communication avec vous :</h4>
            <p>
                Nous pouvons être amenés à vous envoyer des communications, telles que des e-mails ou des notifications au sein des produits, pour vous répondre ou vous informer sur des questions relatives aux produits, sur la recherche ou sur nos conditions et politiques. Pour en apprendre davantage, veuillez consulter notre Politique de confidentialité.
            </p>
        </div>
        <div class="cgu_title">
            <h3>2. Comment nos services sont financés</h3>
            <p>Vous pouvez choisir d’utiliser nos Produits gratuitement avec des publicités ou de vous abonner pour les utiliser sans publicité :</p>
        </div>
        <div class="cgu_description">
            <p>
                Si vous choisissez d’utiliser gratuitement nos Produits avec des publicités, vous nous autorisez à vous afficher des publicités que les entreprises et les organisations nous paient pour promouvoir sur et en dehors des Produits.
                Si vous choisissez de vous abonner pour utiliser nos Produits sans publicité, vous ne verrez pas de publicité de notre part et nous n’utiliserons pas vos données à des fins publicitaires. Les détails du prix, de la devise et de la période de paiement pour l’abonnement sans publicité vous seront fournis avant que vous ne finalisiez votre achat.
                Le respect de la confidentialité est au cœur de la conception de notre système publicitaire. Si nous vous affichons des publicités sur les Produits, nous vous affichons des publicités pertinentes et utiles sans informer les annonceurs de votre identité. Nous ne vendons pas vos informations à caractère personnel et ne partageons pas avec les annonceurs d’informations permettant de vous identifier directement (telles que votre nom, votre adresse e-mail ou toutes autres coordonnées), sauf autorisation expresse de votre part. En revanche, nous autorisons les annonceurs à nous donner des informations, telles que leur objectif commercial et le type d’audience à laquelle ils souhaitent adresser leurs publicités (par exemple, les personnes de 18 à 35 ans qui vivent près du magasin de l’annonceur au Portugal). Puis, nous affichons leur publicité aux personnes qui, selon nous, pourraient la trouver pertinente.
                De plus, nous envoyons aux annonceurs des rapports sur les performances de leurs publicités pour les aider à comprendre comment les personnes interagissent avec leur contenu sur les Produits et en dehors. Par exemple, nous communiquerons aux annonceurs des informations générales concernant la démographie et les centres d’intérêt pour les aider à mieux comprendre leur audience, par exemple le fait qu’une publicité a été vue par des femmes entre 25 et 34 ans qui vivent à Madrid et qui aiment l’ingénierie informatique. Nous ne partageons aucune information qui vous identifie directement (des informations comme votre nom ou adresse e-mail qui, en elles-mêmes, peuvent servir à vous contacter ou à vous identifier) sans avoir obtenu votre autorisation spécifique. En savoir plus sur la manière dont fonctionnent les publicités ici.
                Vous pouvez en apprendre davantage sur la manière dont nous recueillons et utilisons vos informations dans notre Politique de confidentialité. Vous y trouverez notamment plus de détails sur les différents types d’informations que nous utilisons pour vous montrer des publicités (si nous vous affichons des publicités sur le Produits). Vous pouvez contrôler les types de publicités et d’annonceurs que vous voyez ainsi que les types d’informations que nous utilisons pour définir les publicités que nous vous montrons. En savoir plus.
            </p>
        </div>
        <div class="cgu_title">
            <h3>3. Vos engagements envers SportLink et notre communauté</h3>
            <p>Nous fournissons ces services à vous et à d’autres personnes pour faire progresser notre mission. En échange, nous avons besoin que vous preniez les engagements suivants :></p>
        </div>
        <div class="cgu_description">
            <h4>1. Qui peut utiliser SportLink</h4>
            <p>
                Lorsque les personnes répondent de leur avis et de leurs actions, notre communauté est plus sûre et plus responsable. Pour cette raison, vous devez :
                Donner à votre compte le même nom que celui que vous utilisez au quotidien.
                Fournir des informations exactes à votre sujet.
                Créer un seul compte (le vôtre) et l’utiliser à des fins personnelles.
                Ne pas partager votre mot de passe, autoriser d’autres personnes à accéder à votre compte SportLink, ni transférer votre compte à quiconque (sans notre autorisation).
                Nous essayons de rendre SportLink largement accessible à tous, mais vous ne pouvez pas utiliser SportLink si :
                Vous avez moins de 13 ans.
                Vous avez été reconnu coupable de délit sexuel.
                Nous avons désactivé votre compte par le passé pour non-respect de nos Conditions, de nos Standards de la communauté ou de conditions et politiques applicables à votre utilisation de SportLink. Si nous désactivons votre compte en raison d’une violation de nos Conditions, de nos Standards de la communauté ou d’autres conditions et politiques, vous acceptez de ne pas en créer d’autres sans notre autorisation. L’autorisation de créer un nouveau compte est accordée à notre seule discrétion et ne signifie ni n’implique en aucun cas que la mesure disciplinaire était erronée ou injustifiée.
                Il vous est interdit de bénéficier de nos produits, nos services ou nos logiciels en vertu des lois applicables.
            </p>

            <h4>2. Les autorisations que vous nous accordez</h4>
            <p>Nous avons besoin de certaines autorisations de votre part pour pouvoir fournir nos services :</p>
            <h5>1.Autorisation d’utiliser le contenu que vous créez et partagez :</h5>
            <p> 
                Le contenu que vous partagez ou importez, tel que les photos ou les vidéos, peut être protégé par des droits de propriété intellectuelle.
                Vous restez propriétaire du contenu que vous créez et partagez sur SportLink ainsi que sur les autres Produits des entités que vous utilisez, et aucune disposition des présentes Conditions ne vous prive des droits que vous détenez sur votre propre contenu. Vous êtes libre de partager votre contenu avec quiconque, où vous le souhaitez. Afin de nous permettre de fournir nos services, vous devez cependant nous accorder certaines autorisations légales pour utiliser ce contenu.
                Cependant, afin de nous permettre de fournir nos services, vous devez nous accorder certaines autorisations légales (appelées « licences ») pour utiliser ce contenu. Ceci est uniquement dans le but de fournir et d’améliorer nos Produits et services, tels que décrits dans l’article 1 ci-dessus.
                En particulier, lorsque vous partagez, publiez ou importez du contenu protégé par des droits de propriété intellectuelle sur ou en rapport avec nos Produits, vous nous accordez une licence non exclusive, transférable, sous-licenciable, gratuite et mondiale pour héberger, utiliser, distribuer, modifier, exécuter, copier, représenter publiquement ou afficher publiquement, traduire et créer des œuvres dérivées de votre contenu (conformément à vos paramètres de confidentialité et d’application). Cela signifie, par exemple, que si vous partagez une photo sur SportLink, vous nous autorisez à la conserver, à la copier et à la partager avec d’autres (encore une fois, conformément à vos paramètres), tels que les Produits ou des fournisseurs de services qui prennent en charge ces produits et services. La licence prend fin lorsque votre contenu est supprimé de nos systèmes.
                Vous pouvez à tout moment supprimer du contenu individuel que vous partagez, publiez et importez. En outre, tout le contenu publié sur votre compte personnel sera supprimé si vous supprimez votre compte. Découvrez comment supprimer votre compte. La suppression d’un compte n’entraîne pas forcément la suppression du contenu que vous avez publié en tant qu’admin d’une page ou du contenu que vous avez créé collectivement avec d’autres utilisateurs, tel que les photos d’albums partagés, que les autres membres des albums pourront continuer à voir.
                Une fois que nous commençons le processus de suppression du compte ou que nous recevons une demande de suppression de contenu, la suppression peut prendre jusqu’à 90 jours. Si vous placez du contenu dans la corbeille, le processus de suppression commencera automatiquement 30 jours plus tard, sauf si vous choisissez de supprimer le contenu plus tôt. Lorsque le processus de suppression d’un tel contenu débute, les autres utilisateurs ne peuvent plus voir ce contenu. Une fois le contenu supprimé, son retrait des systèmes de sauvegarde et de récupération en cas de sinistre peut prendre jusqu’à 90 jours supplémentaires.
                Le contenu ne sera pas supprimé dans les 90 jours de la suppression du compte ou du début du processus de suppression du contenu dans les situations suivantes :
                votre contenu a été utilisé par des tiers conformément à la présente licence, et ces derniers ne l’ont pas supprimé (dans ce cas, cette licence continuera de s’appliquer jusqu’à la suppression du contenu) ;
                la suppression dans les 90 jours n’est pas possible en raison de limitations techniques de nos systèmes, auquel cas, nous procéderons à la suppression dès que ce sera possible d’un point de vue technique ; ou
                la suppression immédiate limiterait notre faculté à :
                identifier ou enquêter sur des activités illégales ou des violations de nos conditions et politiques (par exemple, identifier ou enquêter sur une utilisation détournée de nos Produits ou systèmes) ;
                protéger la sécurité et l’intégrité de nos Produits, systèmes, services et utilisateurs, et nous défendre ;
                respecter des obligations légales pour la préservation de preuves, en ce compris les données que les entités fournissant des produits et services financiers conservent pour se conformer à toute obligation de tenue de documents requise par la loi ; ou
                nous conformer à la demande d’une autorité judiciaire ou administrative, d’une autorité réglementaire ou d’un organisme gouvernemental ;
                auquel cas, le contenu ne sera pas conservé plus longtemps qu’il n’est nécessaire aux fins pour lesquelles il a été conservé (la durée exacte variant au cas par cas).
                Dans chacun des cas mentionnés ci-dessus, cette licence sera maintenue jusqu’à la suppression complète du contenu.
            </p>
            <h5>2.Autorisation d’utiliser votre nom, votre photo de profil et les informations relatives à vos actions en rapport avec les publicités (si nous vous affichons des publicités sur les Produits) et le contenu commercial ou sponsorisé :</h5>
            <p>
                votre nom et votre photo de profil ainsi que les informations relatives aux actions que vous avez effectuées sur SportLink peuvent être utilisés à côté ou dans le cadre de publicités, d’offres et d’autres contenus sponsorisés ou commerciaux que nous affichons à travers nos Produits, sans qu’aucune compensation ne vous soit versée. Nous pouvons, par exemple, montrer à vos amis que vous êtes intéressé par un évènement promu ou que vous avez aimé une Page SportLink créée par une marque qui nous a payés pour afficher ses publicités sur SportLink. Ce type de publicités et de contenu est uniquement visible par les personnes que vous autorisez à voir les actions que vous avez effectuées sur les Produits. Apprenez-en davantage sur vos paramètres et vos préférences publicitaires.
            </p>

            <h3>4. Dispositions supplémentaires</h3>
            <h4>1. Mise à jour de nos Conditions</h4>
            <p>
                Nous nous efforçons d’améliorer constamment nos services et de développer de nouvelles fonctionnalités afin d’améliorer nos Produits pour vous et notre communauté. Ainsi, nous sommes susceptibles de mettre à jour les présentes Conditions générales de temps à autre afin d’y refléter correctement nos services et nos pratiques, de promouvoir une expérience sûre et sécurisée de nos Produits et de nos services et/ou de nous conformer à la loi applicable. Nous les modifierons uniquement si les dispositions ne sont plus adéquates ou si elles sont incomplètes, et si les modifications sont raisonnables et tiennent compte de vos intérêts, ou si elles sont nécessaires à des fins de sécurité ou de respect de la législation applicable.
                Nous vous informerons (par exemple, par e-mail ou par l’intermédiaire de nos Produits) au moins 30 jours avant de modifier les présentes Conditions générales et vous donnerons l’opportunité de les examiner avant leur entrée en vigueur, à moins que les modifications ne soient requises par la loi. Une fois les Conditions générales mises à jour en vigueur, vous serez lié par celles-ci si vous continuez d’utiliser nos Produits.
                Nous espérons que vous continuerez d’utiliser nos Produits, mais si vous n’êtes pas d’accord avec nos Conditions générales mises à jour et ne souhaitez plus faire partie de la communauté Meta, vous pouvez supprimer votre compte à tout moment.
            </p>
            <h5>2. Suspension ou suppression d’un compte</h5>
            <p>
                Nous voulons faire de SportLink un lieu à la fois chaleureux et sécurisé, où chacun peut s’exprimer et partager ses opinions et ses idé<br>Si nous déterminons que vous avez manifestement, gravement ou à maintes reprises enfreint nos Conditions générales ou Politiques, notamment les Standards de la communauté, nous pouvons suspendre ou désactiver définitivement votre accès aux produits des entités Meta et nous pouvons désactiver définitivement ou supprimer votre compte. Nous pouvons également désactiver ou supprimer votre compte si vous enfreignez à plusieurs reprises des droits de propriété intellectuelle tiers ou si la loi nous y oblige. Apprenez-en plus ici sur la manière dont nous abordons les infractions répétées à nos règles relatives au contenu. Et notre Politique d’utilisation détournée concernant la diffusion fréquente de contenu manifestement illégal peut être consultée ici.<br>Nous pouvons désactiver ou supprimer votre compte s’il n’est pas confirmé après l’enregistrement, s’il n’est pas utilisé et reste inactif pendant une longue période ou si nous déterminons qu’une personne l’a utilisé sans votre autorisation et que nous ne sommes pas parvenus à confirmer que vous êtes bien le propriétaire du compte. Apprenez-en plus sur la manière dont nous désactivons et supprimons des comptes.<br>
                Si nous procédons ainsi, nous vous en informerons et vous expliquerons les options à votre disposition pour demander un réexamen, sauf si cela risque d’engager notre responsabilité juridique ou celle d’un tiers, de porter atteinte à notre communauté d’utilisateurs, ou de compromettre ou d’altérer l’intégrité ou le fonctionnement de l’un de nos services, systèmes ou Produits, ou en cas de restrictions techniques ou lorsqu’il nous est interdit de le faire pour des raisons légales. En savoir plus sur notre processus de gestion des réclamations en cliquant ici<br>
                Apprenez-en davantage sur les dispositions que vous pouvez prendre si votre compte a été désactivé et sur la façon de nous contacter si vous estimez que nous avons désactivé votre compte par erreur.<br>
                Si vous supprimez ou si nous désactivons ou supprimons votre compte, les présentes Conditions générales prendront fin et ne constitueront plus un accord entre vous et nous, mais les dispositions suivantes resteront en vigueur : 3.3.1, 4.2-4.5.
            </p>

            <h5>3. Limites de responsabilité</h5>
            <p>
                Aucune des dispositions des présentes Conditions générales ne vise à exclure ou à limiter notre responsabilité en cas de décès, de blessure physique ou de déclaration erronée et frauduleuse dus à notre négligence, ou dans le but de porter atteinte à vos droits légaux.<br>
                Nous ferons preuve de diligence professionnelle pour vous fournir nos Produits et services, et maintenir un environnement sûr, sécurisé et sans erreur. Sous réserve d’avoir agi avec diligence professionnelle, nous n’acceptons aucune responsabilité en cas de pertes non dues à notre violation des présentes Conditions générales ou à tout autre acte de notre part ; de pertes qui ne sont pas raisonnablement prévisibles par vous ou nous lors de la conclusion des présentes Conditions générales; et d’évènements en dehors de notre contrôle raisonnable.
            </p>
        </div>
    </div>
</div>